markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

timezone: South Korea/Seoul

collections:
  docs:
    output: true

name: Yunjee
description: my websites and blogs
url: https://yunjee.github.io

facebook:
  username: JeeHye Yun

logo: img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions
